# Generated by Django 5.0.6 on 2024-07-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BinInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_number', models.CharField(max_length=6, unique=True)),
                ('bank_name', models.CharField(max_length=255)),
            ],
        ),
    ]
